from crewai import Agent, Task, Crew, Process, LLM

# 1. Point natively to your local running Ollama instance
local_llm = LLM(
    model="ollama/llama3.2",
    base_url="http://localhost:11434"
)

# 2. Define Agent 1: The Infrastructure Architect
architect = Agent(
    role='Principal Network Architect',
    goal='Design high-availability, loop-free core routing configurations.',
    backstory='You are a core infrastructure expert with 15 years of routing and switching experience.',
    verbose=True,
    allow_delegation=False,
    llm=local_llm
)

# 3. Define Agent 2: The Security Auditor
auditor = Agent(
    role='Lead Network Security Engineer',
    goal='Audit network configurations for security flaws, routing loops, and policy anomalies.',
    backstory='You are a veteran security engineer specializing in infrastructure hardening, ACLs, and route-map validation.',
    verbose=True,
    allow_delegation=False,
    llm=local_llm
)

# 4. Define Task 1: Architecture Blueprint Design
task_design = Task(
    description='''Write a precise Cisco IOS-XE configuration for a gateway router performing 
mutual route redistribution between OSPF Process 100 and BGP AS 65001. 
You must use route-maps and apply a specific route tag (e.g., tag 100) to prevent routing loops.''',
    expected_output='A clean Cisco IOS-XE configuration block utilizing route-maps and route tagging.',
    agent=architect
)

# 5. Define Task 2: Security & Risk Audit
task_audit = Task(
    description='''Review the Cisco configuration generated by the architect. 
Verify that the route-map logic successfully blocks recursive routing loops and recommend any 
additional infrastructure hardening commands (like control-plane protection or MD5 authentication).''',
    expected_output='A precise technical assessment verifying the loop prevention logic and listing security recommendations.',
    agent=auditor
)

# 6. Assemble the Pipeline Crew
infrastructure_crew = Crew(
    agents=[architect, auditor],
    tasks=[task_design, task_audit],
    process=Process.sequential,  # Task 1 feeds directly into Task 2
    memory=False                 # Keeps processing light on your Latitude CPU
)

if __name__ == "__main__":
    print("\n## Launching Local Multi-Agent Production Pipeline ##\n")
    result = infrastructure_crew.kickoff()
    print("\n## [Pipeline Complete] Final Combined Output: ##\n")
    print(result)
